Fixed Stored XSS on Hichat
418sec/HiChat pull request #1
Opened 2020-09-04 07:07 UTC by d3m0n-r00t

### 📊 Metadata *

#### Bounty URL: https://www.huntr.dev/bounties/1-npm-hichat

### ⚙️ Description *
The ```HiChat``` application is a simple ```chat``` for ```small teams``` which is based on a ```small server``` which helps to ```track``` messages sent by various users. The project presents a ```stored XSS``` issue which could lead to ```session stealing``` or ```HTML/JS injection``` in a permanent way, until the victim leaves the chat room.
Fixed the stored xss using the sanitize-html module to filter out html tags from the input. 
https://www.npmjs.com/package/sanitize-html

### 💻 Technical Description *
Sanitize-html is a simple sanitizer module, to filter out html tags and sanitize input.

### 🐛 Proof of Concept (PoC) *
  1. Download the project locally
  2. Run npm i
  3.  Run node server
  4. Go on http://localhost:3000
  5.  Join the chat room and set your username as test"><img/src="x"/onerror="alert(document.domain)">
  6.  Open an anonymous tab and join the chatroom as another user (simulating the victim who joins the same chat room of the attacker)
  7.  When the attacker sends any message, the username is insecurely reflected and JS injected
  8.  XSS popped !!!
![hichatpoc](https://user-images.githubusercontent.com/29670330/92209547-d1cdd500-eeaa-11ea-907e-eb615732a5ae.png)

### 🔥 Proof of Fix (PoF) *
Added sanitize-html to sanitize the input and filter out html tags to avoid injecting xss payloads into the ```nickname``` field as well as the ```message``` field. There is no xss after sanitization. 
![hichatpof](https://user-images.githubusercontent.com/29670330/92209657-02157380-eeab-11ea-8598-b0b292431667.png)

### 👍 User Acceptance Testing (UAT)
The application runs smoothly after the fix, and no more xss. Can now send and receive messages without worrying about ```xss``` or ```data leakage```.

2020-09-04 08:26 UTC, 418raj reviewed
LGTM

2020-09-04 09:16 UTC, Mik317 approved these changes
LGTM :smile: :tada:

Cheers,
Mik

2020-09-04 12:02 UTC, alromh87 commented
Unfortunately this fix is bypassable using socket io directly

POC:
1. Run server
2. Connect from browser and select user name
3. create client.js
```
const
    io = require("socket.io-client"),
    ioClient = io.connect("http://localhost:3000/");

ioClient.on("system", (usr,_2,_3) => console.info('system: ', usr));
ioClient.on("newMsg", (usr,msg) => console.info(usr, msg));

ioClient.on('connect', () => {
   console.log('Conectado')
   ioClient.emit('login', 'testUser"><img/src="x"/onerror="alert(\'Login: Hello from console\')">')
   ioClient.emit('postMsg', 'testMesage"><img/src="x"/onerror="alert(\'Msg: Hello from console\')">')
   ioClient.emit('postMsg', '<script>alert("Msg script")</script>')
});
``` 
4. Execute js
```
node client.js
```
5. Script is exected on web browser client

![Captura de pantalla de 2020-09-04 14-58-20](https://user-images.githubusercontent.com/7505980/92237220-a7d2dd80-eebf-11ea-8108-16a6b3339c2a.png)

2020-09-04 12:22 UTC, 418raj commented
Ah interesting - didn't think to try that, cheers. @d3m0n-r00t thoughts?

2020-09-04 12:40 UTC, Mik317 commented
@alromh87 you're right :smile:
I bypassed a similar fix an hour ago with the same technique :joy: 
Validation `server side` always wins :+1: 

Cheers,
Mik

2020-09-04 12:49 UTC, alromh87 commented
Sent updated PR using library

Relevant lines is where data is displayed to user:

https://github.com/418sec/HiChat/commit/c085762871d858ceb18df75b22ca48c2c117552f#diff-a90151b03560b4909234dfd89c452458R146

2020-09-04 14:17 UTC, d3m0n-r00t commented
@alromh87, 
Thanks for letting me know about the bypass. I hadn't though about this attack mode. 
I have added sanitization in input in the server side too. Now it sanitizes input from browser as well as console. 
@Mik317 , @418raj . Please let me know if any problem with the fix. 
Proof-of-fix
![bypasspof](https://user-images.githubusercontent.com/29670330/92248805-dfa14b80-eee6-11ea-822a-1dcf1ddebb03.png)

PS: It is a wonderful bypass. It took me some time reproducing the bug.

2020-09-04 15:57 UTC, Mik317 requested changes
Just rechecked:
* HTML tags are still injectable in part (used the payloads on https://cure53.de/purify) even if no XSS possible
* emoji functionality broken

Cheers,
Mik

2020-09-04 15:57 UTC, Mik317 commented on server.js
> +    sanitizehtml = require('./www/scripts/sanitizehtml.js')
I'm still able to inject some `HTML tags` which could lead to `deface` :smile:

![Screenshot from 2020-09-04 17-52-30](https://user-images.githubusercontent.com/33063403/92260218-da88d000-eed7-11ea-9d8c-7b3d1a31edce.png)

Also, the `emoji` functionality doesn't work well :cry: 

Cheers,
Mik

2020-09-04 17:32 UTC, d3m0n-r00t commented
@Mik317, Nice find. I accidentally sanitized out the emoji. I have added the fix. Cheers.
About you were able to inject ```html``` tags. I have added sanitization in every input. So all the tags that might cause a problem is filtered out. The ```deface``` you say is just the residual gibberish that comes after sanitization and is limited to the message box not the entire website. It is just like a user typing in unwanted messages. It doesn't affect users. I believe that it is not enough to cause a problem and the app seems to be working fine even after the injection. 
Please let me know if I am wrong. 
Thanks

2020-09-07 18:44 UTC, Mik317 approved these changes
LGTM :smile: :tada:

Cheers,
Mik

2020-09-10 09:30 UTC, merged

2020-09-10 09:30 UTC, huntr-helper commented
Congratulations d3m0n-r00t - your fix has been selected! 🎉

Thanks for being part of the community & helping secure the world's open source code.
If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!