Fix Stored XSS
418sec/HiChat pull request #3
Opened 2020-09-04 11:52 UTC by alromh87

### 📊 Metadata *

#### Bounty URL: https://www.huntr.dev/bounties/1-npm-hichat/

### ⚙️ Description *

There is no input sanitization in data provided to server making code injection available to malitious user.

### 💻 Technical Description *

Fixed by sanitizing user and message with  DOMPurify before showing messages.

### 🐛 Proof of Concept (PoC) *

1. Download the project locally
2. Run npm i
3. Run node server
4. Go on http://localhost:3000
5. Join the chat room and set your username as test"><img/src="x"/onerror="alert(document.domain)">
6. Open an anonymous tab and join the chatroom as another user (simulating the victim who joins the same chat room of the attacker)
7.. When the attacker sends any message, the username is insecurely reflected and JS injected
8. XSS popped !!!

### Proof of Fix (PoF) *

After fix No code is executed for remote user

### 👍 User Acceptance Testing (UAT)

After fix functionality is unafected

2020-09-04 15:00 UTC, d3m0n-r00t commented
Hi, @alromh87,
I was going through your fix and it seems awesome. But I found a ```xss payload``` that affects DOMpurify and somehow completely breaks the chat room. Please go through this. 
1. Run the server.
2. Open two web browsers and join in the room.
3. Copy and paste the following payload to the message box.

Payload can be found in this url: https://cure53.de/purify
![bypassdom2](https://user-images.githubusercontent.com/29670330/92253442-1f6b3180-eeed-11ea-80f4-aebb1137b9f3.png)

2020-09-04 15:51 UTC, Mik317 requested changes
@alromh87 :smile:
thank you for your fix :+1: 

I'm still able to inject `html tags` which, even if don't lead directly to `XSS`, make still possible `defacing` the chat and serve eventually malicious content.
I would suggest sanitizing completely the `HTML` tags to avoid these issues :smile:

Cheers,
Mik

2020-09-04 21:46 UTC, alromh87 commented
@d3m0n-r00t 
@Mik317 

Thanks for your help debugging the fix, I updated according to your feedback

Could you try again :wink:

2020-09-07 18:56 UTC, Mik317 approved these changes
LGTM :smile: :tada:

Cheers,
Mik

2020-09-10 09:28 UTC, closed without merging

2020-09-10 09:28 UTC, huntr-helper commented
Sorry alromh87, we enjoyed reviewing your fix but it has not been selected this time. If this bounty has not been closed, please feel free to try again with a new pull request!
        
We appreciate your effort and look forward to reviewing more of your fixes in the future! 🔨😎

2020-09-10 11:04 UTC, alromh87 commented
I would like to ask for review since Accepted fix doesn't handle XSS trough img links.
![Captura de pantalla de 2020-09-10 13-57-18](https://user-images.githubusercontent.com/7505980/92721063-2e7b3500-f36e-11ea-80d3-f4c4c6f21e10.png)
POC
```
const
    io = require("socket.io-client"),
    ioClient = io.connect("http://localhost:3000/");

ioClient.on("system", (usr,_2,_3) => console.info('system: ', usr));
ioClient.on("newMsg", (usr,msg) => console.info(usr, msg));

ioClient.on('connect', () => {
   console.log('Conectado')
   ioClient.emit('login', 'testUser"><img/src="x"/onerror="alert(\'Login: Hello from console\')">')
   ioClient.emit('postMsg', 'testMesage"><img/src="x"/onerror="alert(\'Msg: Hello from console\')">')
   ioClient.emit('postMsg', '<script>alert("Msg script")</script>')
   ioClient.emit('postMsg', 'testMesage"><img/src="x"/onerror="alert(\'Msg: Hello from console\')">[emoji:5] yeah!!')
   ioClient.emit('img', 'age"><img/src="x"/onerror="alert(\'Image: Hello from console\')">[emoji:5] yeah!!')
   ioClient.emit('img', 'javascript:alert(\'Img link: Hello again\')')
   ioClient.emit('img', 'javascript:jjavascript:ajavascript:vjavascript:ajavascript:sjavascript:cjavascript:rjavascript:ijavascript:pjavascript:t://test%0Aalert(1)')
});
```

And also looses some text

I would also like to point out that is safer to threat messages as text instead of trying to clean html **(which can be bypassable)** and evaluate in on the browser

2020-09-10 11:32 UTC, JamieSlome commented
@alromh87 - We understand your point.

Could you explain why the usage of `sanitizeHtml` around `imgData` is not sufficient on L42 of server.js?

Cheers! 🍰

2020-09-10 11:43 UTC, alromh87 commented
Since image data received is used for both image and to create the link to it, and sanitizeHtml will not handle javascript:

leading to a link like <a href="javascript:alert(...)">

That will execute code when user intends to see the image
![Captura de pantalla de 2020-09-10 14-40-50](https://user-images.githubusercontent.com/7505980/92724779-d34c4100-f373-11ea-9381-0d0213b47d7c.png)

2020-09-10 13:37 UTC, 418raj commented
Had a quick look - validated that. I saw you used dompurify as a fix for this - good call - we'll merge that section in as a 'catch-all" for injection through images. Have added the credits for this to your account - cheers 👍

2020-09-10 13:47 UTC, alromh87 commented
DOMpurify will not catch the javascript, clined the input before emiting the message:

https://github.com/418sec/HiChat/pull/3/files#diff-78c12f5adc1848d13b1c6f07055d996eL41